# Generated by Django 4.0.4 on 2023-03-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_coin_alter_card_color_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('purple', 'purple'), ('blue', 'blue'), ('orange', 'orange'), ('green', 'green')], default='purple', max_length=10),
        ),
    ]
