# Generated by Django 4.0.4 on 2023-03-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_alter_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('purple', 'purple'), ('blue', 'blue'), ('green', 'green'), ('orange', 'orange')], default='purple', max_length=10),
        ),
    ]
