# Generated by Django 4.0.4 on 2023-03-24 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coins', '0005_alter_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('green', 'green'), ('purple', 'purple'), ('orange', 'orange'), ('blue', 'blue')], default='purple', max_length=10),
        ),
        migrations.CreateModel(
            name='CoinCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='coins.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curency', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
