# Generated by Django 4.0.4 on 2023-03-27 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coins', '0006_alter_card_color_coincurrency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coincurrency',
            options={'verbose_name': 'currency', 'verbose_name_plural': 'currencies'},
        ),
        migrations.AddField(
            model_name='card',
            name='balance',
            field=models.FloatField(default=15000),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('green', 'green'), ('purple', 'purple'), ('blue', 'blue'), ('orange', 'orange')], default='purple', max_length=10),
        ),
        migrations.AlterField(
            model_name='coincurrency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to=settings.AUTH_USER_MODEL),
        ),
    ]
